### ISSUE TITLE
Extend doofinder feed

### ISSUE THREAD

**Issue by camlafit** [doofinder/doofinder-prestashop-deprecated#44]
Actually feed exporter must overwritten completely to add new fields.

Should be nice to add a hook to allow external module to extend header and new column.

An use case is to ad df_rating in the feed. Module natively can't manage this feature because we can have different solution to manage product rating.
With hook we could extend feed without overwritting.

**Comment by danidomen** [comment]
Hi @camlafit,

Please, make the pull request on this repo https://github.com/danidomen/doofinder, because on this (doofinder/doofinder-prestashop) only exists an old version of the module.

**Comment by camlafit** [comment]
Hello @danidomen 

Is not useful :/ You're repo is not a fork from doofinder/doofinder-prestashop

**Comment by camlafit** [comment]
Hello

Should be done with https://github.com/danidomen/doofinder/pull/2

**Comment by camlafit** [comment]
As is not official doofinder module.I close here and continue on official repository.
